apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pfa
  namespace: argocd
spec:
  project: gitops
  source:
    repoURL: https://github.com/COOBRA01/app-gitops
    targetRevision: main
    path: manifests
    directory:
      exclude: argocd-app.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true