apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: evaander/your-app-django:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "mysql://django_user:password123@db:3306/admin"
        - name: DEBUG
          value: "0"
      - name: queue
        image: evaander/your-app-django:latest
        command: ["python", "-u", "consumer.py"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "admin.settings"
---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: prod
spec:
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: django
  type: NodePort