apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: evaander/your-app-django:6a32a53
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_PASSWORD
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_URL
        - name: DEBUG
          value: "0"
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /api/products
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /api/products
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 10

      - name: queue
        image: evaander/your-app-django:6a32a53
        command: ["python", "-u", "consumer.py"]
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: "admin.settings"
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_URL
        resources:
          limits:
            cpu: "150m"
            memory: "256Mi"
          requests:
            cpu: "50m"
            memory: "128Mi"
        livenessProbe:
          exec:
            command: ["python", "-c", "import pika, os; pika.BlockingConnection(pika.URLParameters(os.getenv('RABBITMQ_URL')))"]
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: django
  namespace: prod
spec:
  type: NodePort
  selector:
    app: django
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
