apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-db
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-db
  template:
    metadata:
      labels:
        app: django-db
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password123"
        - name: MYSQL_USER
          value: "django_user"
        - name: MYSQL_PASSWORD
          value: "password123"
        - name: MYSQL_DATABASE
          value: "admin"
        volumeMounts:
        - name: django-db-data
          mountPath: /var/lib/mysql
      volumes:
      - name: django-db-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: django-db
  namespace: prod
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: django-db