apiVersion: batch/v1
kind: Job
metadata:
  name: flask-migrate
  namespace: prod
spec:
  template:
    spec:
      containers:
      - name: migrate
        image: evaander/your-app-flask:latest
        command: ["/bin/sh", "-c", "flask db migrate && flask db upgrade"]
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: MYSQL_PASSWORD
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: RABBITMQ_URL
        - name: DATABASE_URL
          value: "mysql://$(MYSQL_USER):$(MYSQL_PASSWORD)@db:3306/main"
        restartPolicy: Never
  backoffLimit: 4